-- ============================================================================
-- ATS Database Schema - PostgreSQL DDL
-- Generated from ERD Mermaid diagram
-- ============================================================================

-- Enable UUID extension if needed (optional, using INT for now)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- TABLES
-- ============================================================================

-- Company table
CREATE TABLE IF NOT EXISTS company (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Employee table
CREATE TABLE IF NOT EXISTS employee (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_employee_company FOREIGN KEY (company_id) 
        REFERENCES company(id) ON DELETE CASCADE
);

-- Interview Type table (catalog)
CREATE TABLE IF NOT EXISTS interview_type (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Interview Flow table
CREATE TABLE IF NOT EXISTS interview_flow (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Interview Step table
CREATE TABLE IF NOT EXISTS interview_step (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_flow_id INT NOT NULL,
    interview_type_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    order_index INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_interview_step_flow FOREIGN KEY (interview_flow_id) 
        REFERENCES interview_flow(id) ON DELETE CASCADE,
    CONSTRAINT fk_interview_step_type FOREIGN KEY (interview_type_id) 
        REFERENCES interview_type(id) ON DELETE RESTRICT,
    CONSTRAINT chk_order_index_positive CHECK (order_index > 0)
);

-- Position table
CREATE TABLE IF NOT EXISTS position (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    interview_flow_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    is_visible BOOLEAN NOT NULL DEFAULT FALSE,
    location VARCHAR(255),
    job_description TEXT,
    requirements TEXT,
    responsibilities TEXT,
    salary_min NUMERIC(10, 2),
    salary_max NUMERIC(10, 2),
    employment_type VARCHAR(50) NOT NULL DEFAULT 'full-time',
    benefits TEXT,
    company_description TEXT,
    application_deadline DATE,
    contact_info VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_position_company FOREIGN KEY (company_id) 
        REFERENCES company(id) ON DELETE CASCADE,
    CONSTRAINT fk_position_interview_flow FOREIGN KEY (interview_flow_id) 
        REFERENCES interview_flow(id) ON DELETE RESTRICT,
    CONSTRAINT chk_salary_range CHECK (salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max),
    CONSTRAINT chk_status CHECK (status IN ('draft', 'open', 'closed', 'cancelled')),
    CONSTRAINT chk_employment_type CHECK (employment_type IN ('full-time', 'part-time', 'contract', 'internship', 'freelance'))
);

-- Candidate table (extending existing schema)
CREATE TABLE IF NOT EXISTS candidate (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(15),
    address VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Application table
CREATE TABLE IF NOT EXISTS application (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id INT NOT NULL,
    candidate_id INT NOT NULL,
    application_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_application_position FOREIGN KEY (position_id) 
        REFERENCES position(id) ON DELETE CASCADE,
    CONSTRAINT fk_application_candidate FOREIGN KEY (candidate_id) 
        REFERENCES candidate(id) ON DELETE RESTRICT,
    CONSTRAINT chk_application_status CHECK (status IN ('pending', 'reviewing', 'interviewing', 'offered', 'rejected', 'withdrawn'))
);

-- Interview table
CREATE TABLE IF NOT EXISTS interview (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INT NOT NULL,
    interview_step_id INT NOT NULL,
    employee_id INT NOT NULL,
    interview_date DATE NOT NULL,
    result VARCHAR(50),
    score INT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_interview_application FOREIGN KEY (application_id) 
        REFERENCES application(id) ON DELETE CASCADE,
    CONSTRAINT fk_interview_step FOREIGN KEY (interview_step_id) 
        REFERENCES interview_step(id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_employee FOREIGN KEY (employee_id) 
        REFERENCES employee(id) ON DELETE RESTRICT,
    CONSTRAINT chk_interview_result CHECK (result IS NULL OR result IN ('passed', 'failed', 'pending', 'cancelled')),
    CONSTRAINT chk_score_range CHECK (score IS NULL OR (score >= 0 AND score <= 100))
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Employee indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_employee_email_unique ON employee(email);
CREATE INDEX IF NOT EXISTS idx_employee_company_id ON employee(company_id);
CREATE INDEX IF NOT EXISTS idx_employee_is_active ON employee(is_active);

-- Candidate indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_candidate_email_unique ON candidate(email);
CREATE INDEX IF NOT EXISTS idx_candidate_name ON candidate(last_name, first_name);

-- Position indexes
CREATE INDEX IF NOT EXISTS idx_position_company_id ON position(company_id);
CREATE INDEX IF NOT EXISTS idx_position_status ON position(status);
CREATE INDEX IF NOT EXISTS idx_position_is_visible ON position(is_visible);
CREATE INDEX IF NOT EXISTS idx_position_company_status_visible ON position(company_id, status, is_visible);

-- Application indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_application_position_candidate_unique ON application(position_id, candidate_id);
CREATE INDEX IF NOT EXISTS idx_application_candidate_id ON application(candidate_id);
CREATE INDEX IF NOT EXISTS idx_application_position_id ON application(position_id);
CREATE INDEX IF NOT EXISTS idx_application_status ON application(status);
CREATE INDEX IF NOT EXISTS idx_application_candidate_status ON application(candidate_id, status);

-- Interview indexes
CREATE INDEX IF NOT EXISTS idx_interview_application_id ON interview(application_id);
CREATE INDEX IF NOT EXISTS idx_interview_interview_step_id ON interview(interview_step_id);
CREATE INDEX IF NOT EXISTS idx_interview_employee_id ON interview(employee_id);
CREATE INDEX IF NOT EXISTS idx_interview_application_step ON interview(application_id, interview_step_id);
CREATE INDEX IF NOT EXISTS idx_interview_date ON interview(interview_date);

-- Interview Step indexes
CREATE INDEX IF NOT EXISTS idx_interview_step_flow_id ON interview_step(interview_flow_id);
CREATE INDEX IF NOT EXISTS idx_interview_step_flow_order ON interview_step(interview_flow_id, order_index);

-- Interview Flow indexes
CREATE INDEX IF NOT EXISTS idx_interview_flow_description ON interview_flow(description);

-- ============================================================================
-- TRIGGERS FOR updated_at
-- ============================================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for each table
CREATE TRIGGER update_company_updated_at BEFORE UPDATE ON company
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_employee_updated_at BEFORE UPDATE ON employee
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_interview_type_updated_at BEFORE UPDATE ON interview_type
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_interview_flow_updated_at BEFORE UPDATE ON interview_flow
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_interview_step_updated_at BEFORE UPDATE ON interview_step
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_position_updated_at BEFORE UPDATE ON position
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_candidate_updated_at BEFORE UPDATE ON candidate
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_application_updated_at BEFORE UPDATE ON application
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_interview_updated_at BEFORE UPDATE ON interview
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE company IS 'Companies that post job positions';
COMMENT ON TABLE employee IS 'Employees of companies who conduct interviews';
COMMENT ON TABLE interview_type IS 'Catalog of interview types (Phone Screen, Tech Interview, etc.)';
COMMENT ON TABLE interview_flow IS 'Interview flows assigned to positions';
COMMENT ON TABLE interview_step IS 'Steps within an interview flow';
COMMENT ON TABLE position IS 'Job positions posted by companies';
COMMENT ON TABLE candidate IS 'Job candidates applying for positions';
COMMENT ON TABLE application IS 'Applications submitted by candidates for positions';
COMMENT ON TABLE interview IS 'Interview records for applications';

COMMENT ON COLUMN position.status IS 'Position status: draft, open, closed, cancelled';
COMMENT ON COLUMN position.employment_type IS 'Employment type: full-time, part-time, contract, internship, freelance';
COMMENT ON COLUMN application.status IS 'Application status: pending, reviewing, interviewing, offered, rejected, withdrawn';
COMMENT ON COLUMN interview.result IS 'Interview result: passed, failed, pending, cancelled';
COMMENT ON COLUMN interview.score IS 'Interview score from 0 to 100';

